### ISSUE TITLE
bugsnag-asgi?

### ISSUE THREAD

**Issue by florimondmanca** [ashinabraham/starlette-bugsnag#1]
Hi,

This little middleware looks really good, nice work!

Looking at the code, Starlette doesn't actually seem to be a dependency to this project. The middleware implements the ASGI interface, so it should be interoperable with any ASGI server/framework.

Could it be that this could have been `bugsnag-asgi`?

**Comment by ashinabraham** [comment]
Hi,

Sorry for the late reply, I haven't added Starlette to the dependency. As
far as I know, Starlette is the only ASGI framework that is on production.
So as the Middleware is the beta stage, I haven't seen a point in adding
Starlette to the dependency,
Also, I want this middleware to accommodate all future ASGI framework. Also
when I checked bugsnag-asgi,  there is another project and it's an 
obsolete code.
Now Starlette is using ASGI 3 version and bugsnag-asgi doesn't work with
the current version of the Starlette.

**Comment by florimondmanca** [comment]
I imagine you refer to [bugsnag-asgi](https://github.com/steinnes/bugsnag-asgi) by @steinnes?

Pretty sure he’d accept PRs to help upgrade the project to work with ASGI3. :) Probably best to not duplicate work and projects?

**Comment by steinnes** [comment]
Yes, I never got around to updating bugsnag-asgi for asgi3.

Looking at this project I can see there is definitely some DNA which seems to originate in https://github.com/steinnes/bugsnag-asgi (which I'll take as a complement, even though you referred to my project as "an obsolete code" :-)

I'd love to get another maintainer on the project and even let you just take it over, since I am not able to maintain it very actively at the moment.

**Comment by ashinabraham** [comment]
Yes, I started the project by referring [bugsnag-asgi ](https://github.com/steinnes/bugsnag-asgi ) by @steinnes. But I am thinking of merging these two projects into one. so that both works will be available and the middleware will support both ASGI versions.
